### PR TITLE
Add Portuguese (Brazil) Translation 🇧🇷

### PR DESCRIPTION
**Pull request by kiq7**
What this PR does?

Add 🇧🇷Portuguese (Brazil) translation:

readme
roadmap as xml
roadmap as png

cc @adam-golab

### CODE REVIEW

**Comment by adam-golab** [comment]
Hi @kiq7,
I saw it, looks ok for me (but I don't know Portuguese, so maybe someone else could confirm if the translation is correct).
But currently, I'm working on a web application of the Roadmap to provide a more friendly way for translations. For now, any change causes a lot of conflicts with PRs, so it's close to impossible to manage a few languages in current form.
Thanks for your contribution, I will merge it as soon as it will be possible without adding additional work to do.

**Comment by kiq7** [comment]
hey, @adam-golab, no problem ...

I solved some conflicts and everything is fine.

Thank you so much for this.

**Comment by adam-golab** [comment]
Could you also change year to 2019 in all files added by you?

**Comment by kiq7** [comment]
@adam-golab done!

**Comment by adam-golab** [comment]
Thanks @kiq7 !
So, I'm merging it right now

**Pull request merged**
