### PR TITLE
Adding PDF version

### PR DESCRIPTION
**Pull request by prosimplecoding**
_Adding PDF version via upload._

Features of PDF:
- Without losing quality even increased size;
- Printable version;

### CODE REVIEW

**Comment by adam-golab** [comment]
Could you add links to blocks with libraries in the PDF file?
For example, clicking on `React` should navigate to https://reactjs.org/, clicking on `Redux` to https://redux.js.org/ and so on, according to links in the readme. That was probably the idea behind #12. I agree that may be helpful.

**Comment by prosimplecoding** [comment]
Yes, I'm trying to do it. But, text-decoration: none; (in draw.io maybe text-decoration=none; ) CSS rule doesn't work.  
link

**Comment by prosimplecoding** [comment]
One example you can see in this file
[roadmap (Link only added to React).pdf](https://github.com/adam-golab/react-developer-roadmap/files/2173923/react-developer-roadmap.1.with.link.pdf)
**If you agree, I continue like this.**

**Comment by adam-golab** [comment]
I'd prefer a version without underlines and blue color of the font. The link works very well, but I think the roadmap looks better without underlines.

**Comment by adam-golab** [comment]
@prosimplecoding In which way are you adding links? I added link by selecting block, clicking on `Edit` -> `Edit Link...`, and it added link without underline, but I'm not able to export it to single page PDF file. 
But after exporting it to PDF divided into a few pages, it works like a charm.

**Comment by prosimplecoding** [comment]
I also try to find how to make a PDF version links without underlines and blue color of the font using **XML**.

**Comment by prosimplecoding** [comment]
I fixed this problem. More in next pull request.

**Pull request closed without merging**
